@echo off
echo Starting AlloyTower Real Estate Dashboard...
echo.
echo Activating virtual environment...
call .venv\Scripts\activate.bat
echo.
echo Starting Streamlit app...
python -m streamlit run run_app.py
